import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { MarketingAttributionProvider } from "@/components/marketing/MarketingAttributionProvider";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://medexia-akt.com"),
  alternates: {
    canonical: "https://medexia-akt.com",
  },
  title: {
    default:
      "MRCGP AKT Revision — The Whole AKT in 90 Hours of Audio",
    template: "%s | Medexia",
  },
  description:
    "MRCGP AKT audio revision with free syllabus-mapped questions, mocks and 90+ hours of audio. Free until 8 July; £59 Early Access before then, £79 from 8 July.",
  keywords: [
    "AKT",
    "MRCGP AKT",
    "RCGP AKT",
    "AKT exam",
    "Applied Knowledge Test",
    "AKT revision",
    "AKT revision plan",
    "AKT revision timetable",
    "AKT audio revision",
    "AKT audiobook",
    "AKT question bank",
    "AKT mock exam",
    "AKT exam dates",
    "AKT exam format",
    "AKT exam day",
    "Pearson VUE AKT",
    "AKT pass rate",
    "AKT results",
    "AKT retake",
    "AKT feedback reports",
    "AKT consulting",
    "AKT consulting in general practice",
    "AKT shared decision making",
    "AKT consent",
    "AKT safety netting",
    "AKT statistics",
    "AKT statistics formulas",
    "AKT NNT",
    "AKT sensitivity specificity",
    "AKT evidence in practice",
    "AKT critical appraisal",
    "AKT evidence based practice",
    "AKT study design",
    "AKT confidence intervals",
    "AKT prescribing",
    "AKT medication safety",
    "AKT medication monitoring",
    "AKT quality improvement",
    "AKT patient safety",
    "AKT continuity quality safety prescribing",
    "AKT continuity of care",
    "AKT audit cycle",
    "AKT significant event analysis",
    "AKT confidentiality",
    "AKT safeguarding",
    "AKT data protection",
    "AKT neurology",
    "AKT gait disturbance",
    "AKT headache red flags",
    "AKT children",
    "AKT paediatrics",
    "AKT paediatric cancer",
    "AKT dermatology",
    "AKT skin cancer",
    "AKT rashes",
    "AKT cardiovascular",
    "AKT hypertension",
    "AKT atrial fibrillation",
    "AKT heart failure",
    "AKT respiratory",
    "AKT asthma",
    "AKT COPD",
    "AKT inhalers",
    "AKT diabetes",
    "AKT endocrinology",
    "AKT thyroid",
    "AKT sick day rules",
    "AKT renal",
    "AKT urology",
    "AKT CKD",
    "AKT UTI",
    "AKT musculoskeletal",
    "AKT back pain",
    "AKT osteoarthritis",
    "AKT rheumatoid arthritis",
    "AKT gastroenterology",
    "AKT IBS",
    "AKT IBD",
    "AKT coeliac",
    "AKT ENT",
    "AKT hearing loss",
    "AKT vertigo",
    "AKT otitis media",
    "AKT eyes",
    "AKT vision",
    "AKT red eye",
    "AKT glaucoma",
    "AKT haematology",
    "AKT anaemia",
    "AKT VTE",
    "AKT anticoagulation",
    "AKT allergy",
    "AKT immunology",
    "AKT anaphylaxis",
    "AKT food allergy",
    "AKT infectious diseases",
    "AKT travel health",
    "AKT HIV",
    "AKT hepatitis",
    "AKT malaria",
    "AKT minor illness",
    "AKT urgent care",
    "AKT sepsis",
    "AKT delayed antibiotics",
    "AKT mental health",
    "AKT depression",
    "AKT suicide risk",
    "AKT SSRI",
    "AKT women's health",
    "AKT contraception",
    "AKT menopause",
    "AKT HRT",
    "AKT maternity",
    "AKT reproductive health",
    "AKT pregnancy",
    "AKT antenatal care",
    "AKT postnatal care",
    "AKT sexual health",
    "AKT STI",
    "AKT chlamydia",
    "AKT HIV testing",
    "AKT older adults",
    "AKT frailty",
    "AKT falls",
    "AKT dementia",
    "AKT urgent care",
    "AKT sepsis",
    "AKT NEWS2",
    "AKT anaphylaxis",
    "AKT smoking cessation",
    "AKT alcohol misuse",
    "AKT substance misuse",
    "AKT AUDIT",
    "AKT population health",
    "AKT planetary health",
    "AKT screening",
    "AKT immunisation",
    "AKT health inequalities",
    "AKT long-term conditions",
    "AKT cancer",
    "AKT cancer red flags",
    "AKT multimorbidity",
    "AKT end of life",
    "AKT palliative care",
    "AKT DNACPR",
    "AKT anticipatory medicines",
    "AKT learning disability",
    "AKT annual health checks",
    "AKT diagnostic overshadowing",
    "AKT reasonable adjustments",
    "AKT equality diversity inclusion",
    "AKT interpreters",
    "AKT inclusive care",
    "AKT accessible information",
    "AKT leadership management",
    "AKT raising concerns",
    "AKT complaints",
    "AKT practice systems",
    "AKT genomic medicine",
    "AKT genetics",
    "AKT inheritance patterns",
    "AKT familial cancer",
    "AKT neurodiversity",
    "AKT neurodevelopmental conditions",
    "AKT ADHD",
    "AKT autism",
    "AKT syllabus",
    "AKT curriculum",
    "AKT exam fee",
    "AKT eligibility",
    "AKT evidence based practice",
    "MRCGP revision",
    "GP training",
    "AKT Navigator",
    "Medexia",
    "free AKT questions",
  ],
  openGraph: {
    title: "MRCGP AKT Revision — The Whole AKT in 90 Hours of Audio",
    description:
      "Free syllabus-mapped AKT questions, mocks and 90+ hours of audio across all 32 topics. Free until 8 July; £59 Early Access before then, £79 from 8 July.",
    type: "website",
    url: "https://medexia-akt.com",
    siteName: "AKT Navigator by Medexia",
    // og:image auto-wired from src/app/opengraph-image.tsx — do not set
    // `images` here or it overrides the file-based convention.
  },
  twitter: {
    card: "summary_large_image",
    title: "MRCGP AKT Revision — The Whole AKT in 90 Hours of Audio",
    description:
      "Free syllabus-mapped AKT questions, mocks and 90+ hours of audio across all 32 topics. Free until 8 July; £59 Early Access before then, £79 from 8 July.",
    // twitter:image auto-wired from src/app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://medexia-akt.com/#organization",
      name: "Medexia",
      legalName: "Medexia Ltd",
      alternateName: "Medexia AKT Navigator",
      url: "https://medexia-akt.com",
      logo: {
        "@type": "ImageObject",
        url: "https://medexia-akt.com/app-icon.png",
      },
      email: "support@medexia-akt.com",
      description:
        "Medexia builds AKT Navigator, an independent audio-first revision resource for the RCGP MRCGP Applied Knowledge Test (AKT). It is not affiliated with, or endorsed by, the Royal College of General Practitioners.",
      knowsAbout: [
        "MRCGP Applied Knowledge Test",
        "AKT revision",
        "GP specialty training",
        "Audio-based medical education",
      ],
    },
    {
      "@type": "WebSite",
      "@id": "https://medexia-akt.com/#website",
      name: "AKT Navigator by Medexia",
      url: "https://medexia-akt.com",
      inLanguage: "en-GB",
      description:
        "Audio-first MRCGP AKT revision: free syllabus-mapped questions, timed mock exams, deep structured explanations and 90+ hours of audio across all 32 RCGP curriculum topics.",
      publisher: {
        "@id": "https://medexia-akt.com/#organization",
      },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>
        <MarketingAttributionProvider>{children}</MarketingAttributionProvider>
        <Analytics />
      </body>
    </html>
  );
}
